[tox]
envlist =
    3.{10-}
    format
    lint
isolated_build = true
requires =
    tox>=4.55
    tox-uv>=1.35

[testenv]
description = run tests on Python {py_dot_ver}
deps =
    pytest
commands =
    pytest

[testenv:format]
description = format
skip_install = true
deps =
    ruff
commands =
    ruff check tap_zendesk/
    ruff format tap_zendesk/

[testenv:lint]
description = lint
base_python_file = .python-version
deps =
    mypy
    pytest
    ruff
    types-requests
commands =
    ruff check --diff tap_zendesk/
    ruff format --check tap_zendesk/
    mypy .
